# Generated by Django 5.1.5 on 2025-02-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
